[DEFAULT]
debian-branch = mobian-sm7150-6.18
debian-tag = mobian/sm7150-%(version)s
upstream-tag = upstream/%(version)s
upstream-branch = linux-6.18.y
upstream-vcs-tag = v%(version)s
pristine-tar = false

[dch]
commit-msg = d/changelog: release version %(version)s
