[DEFAULT]
debian-branch = mobian-sc7280-6.13
debian-tag = mobian/sc7280-%(version)s
upstream-tag = upstream/%(version)s
upstream-branch = linux-6.13.y
upstream-vcs-tag = v%(version)s
pristine-tar = false

[dch]
commit-msg = d/changelog: release version %(version)s
