[DEFAULT]
debian-branch = mobian-sm6350-6.17
debian-tag = mobian/sm6350-%(version)s
upstream-tag = upstream/%(version)s
upstream-branch = linux-6.17.y
upstream-vcs-tag = v%(version)s
pristine-tar = false

[dch]
commit-msg = d/changelog: release version %(version)s
